# Generated by Django 4.1.3 on 2022-11-26 18:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carro',
            name='ano',
        ),
    ]
